### ISSUE TITLE
CLI Inputs/outputs

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#43]
Opening the issue to discuss the CLI design. Below are some of my thoughts of the possible designs. 

The command line neuroscout interface will download a pre-compiled python file which is a complete nipype workflow that is executed using `python-datalad`  to download all the necessary files. Files in the script will be referenced with relative paths as in `src/{dataset}/{file}`. 

The command line interface will also need to retrieve `events.tsv` or JSON bundle of the extracted features selected for an analysis in order to execute the workflow.

Alternatively, the CLI could obtain a "bundle" that includes JSON representations necessary to compile the workflow These would reference: the input file paths, the transformations, selected predictors. The CLI woudl then compile and execute the workflow. An advantage of this approach is that we can write a single generic workflow that take these inputs for use on the client and server, rather than having to create a static workflow on the server for download. I've already created such a workflow (see: `scripts/fmri_bids_firstlevel.py`) and it would simply have to be expanded further (and run with `python-datalad`).

However, this approach is potentially problematic as the client and server could have different versions of the workflow, and users could edit the inputs in between.

**Comment by adelavega** [comment]
I think the above solution makes sense, but the CLI can also download the latest workflow (or the workflow used to compile the analysis), rather than relying on an internal version. It will also download a JSON analysis bundle, new event files (or include in JSON bundle, then convert to pandas and pass to pybids transformer).

**Comment by tyarkoni** [comment]
Agree with above, with the caveat that `update` command should be a separate part of the CLI, rather than a part of each analysis. I.e., updating the workflow used to run the analysis can be explicitly done with `neuroscout update`. If the user tries to run an analysis that isn't compatible with the current version (typically because the analysis expects a newer version of the workflow), the user will get a message saying something like "neuroscout is out of data and cannot execute analysis a28da94; please updating your workflow engine by running `neuroscout update`". As we discussed a couple of weeks ago, this makes it so all the Python and imaging dependencies are tied to a specific single version of the CLI tools.

**Comment by adelavega** [comment]
Could there be a situation where an analysis expects an older version of the workflow? For example, if an analysis was created long ago, and upgrades to the workflow occurred prior to the user executing the workflow.

I supposed if we make new version of the workflow backwards compatible, we should be ok, but I could see that getting tricky. Especially if we were to release an update that break backwards compatibility, but perhaps that's easy to avoid.
