### ISSUE TITLE
Analysis bundle endpoint

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#47]
Although I've left `predictor-events` as repetition json objects, for a final download from the `CLI`, a bundle which includes *all* dependencies makes sense.

**Comment by adelavega** [comment]
UPDATE: Add an endpoint that downloads all files required for analysis (aside from original BIDS dataset).

**Comment by tyarkoni** [comment]
What kind of dependencies? I think that, at least in the beginning, there shouldn't be anything to download on an analysis-by-analysis. I.e., all analyses created with the UI should have the same dependencies. So it would probably make sense to build all dependencies into the NeuroDebian and/or Docker images, so that all that's downloaded when a user executes an analysis on the CLI are the event files, model spec, etc.

**Comment by adelavega** [comment]
I didn't mean library dependencies. I meant more like all of the configuration + event files + python script (maybe. to ensure same script that was used to compiled is used to run)

**Comment by adelavega** [comment]
Closed with #113
